### ISSUE TITLE
Runtime error [linux/wayland]

### ISSUE THREAD

**Issue by szbergeron** [Kethku/neovide#22]
Running on wlroots/wayfire nightly

``
UI thread spawned
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_EXTENSION_NOT_PRESENT)))', src/libcore/result.rs:1165:5
``

Not really sure how to interpret that

Excited to try this out :)

Backtrace: 
```   0:     0x560b765965c4 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x560b765965c4 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x560b765965c4 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x560b765965c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x560b765bc94c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x560b76593707 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x560b76598b1e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x560b76598b1e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x560b76598b1e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x560b76598811 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x560b7659921b - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x560b76598dbe - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x560b76598ca6 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x560b765b8f2e - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  14:     0x560b765b9027 - core::result::unwrap_failed::h054dd680e6fcd38b
                               at src/libcore/result.rs:1165
  15:     0x560b75acebc8 - core::result::Result<T,E>::expect::hc1839edd54c6f838
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16:     0x560b75b268ce - neovide::window::ui_loop::hf489ea8a4c132419
                               at src/window.rs:33
  17:     0x560b75b58869 - neovide::main::hb173d805ca0cff3b
                               at src/main.rs:91
  18:     0x560b75b159b0 - std::rt::lang_start::{{closure}}::hd2e582def15a1f35
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  19:     0x560b76598c43 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  20:     0x560b76598c43 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  21:     0x560b765a0f9a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  22:     0x560b765996fd - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  23:     0x560b765996fd - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  24:     0x560b765996fd - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  25:     0x560b75b15989 - std::rt::lang_start::hd66b798f2bf5a03c
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  26:     0x560b75b588ea - main
  27:     0x7f51819ba153 - __libc_start_main
  28:     0x560b75ac3f8e - _start
  29:                0x0 - <unknown>```

**Comment by Kethku** [comment]
I suspect this is due to the rendering library I use which depends on Vulcan to run properly. I don't know what the support story is like for running skia with Vulcan in Linux/wayland. Do you have any ideas?

**Comment by szbergeron** [comment]
Not sure, almost thought it would just work but I may be mistaken

**Comment by Kethku** [comment]
I think Vulcan support on Linux is slightly shaky but Im really not familiar. Maybe make an issue on the skulpin GitHub project? I use that library to do the skia Vulcan interop so maybe they might be able to help

**Comment by szbergeron** [comment]
Forgot to install intel-vulkan (thought it was installed by default), getting an error somewhere else in the stack now but I think this can be closed as just a configuration issue my side

**Comment by sijad** [comment]
i had to install `vulkan-intel` via pacman, maybe this should suggested in README.md?

**Comment by Kethku** [comment]
That should definitely be in the readme. Any chance you could make a PR? If not I'll get to it soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sijad** [comment]
Sorry I'm not sure what package ubuntu user need to install?

**Comment by Kethku** [comment]
I'm not sure either. Although it looks like somebody else got to the readme PR and I am working on integrating it now.
