### ISSUE TITLE
provide instructions for mac to build

### ISSUE THREAD

**Issue by prabirshrestha** [Kethku/neovide#30]
Currently I'm using `brew cask install apenngrace/vulkan/vulkan-sdk` and it runs properly.

<details>
<summary>log</summary>

```
UI thread spawned
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(LoadingError(LibraryLoadError("dlopen(libvulkan.dylib, 1): image not found")))', src/libcore/result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: core::result::Result<T,E>::expect
             at /rustc/99b89533d4cdf7682ea4054ad0ee36c351d05df1/src/libcore/result.rs:983
  15: neovide::window::ui_loop
             at src/window.rs:42
  16: neovide::main
             at src/main.rs:91
  17: std::rt::lang_start::{{closure}}
             at /rustc/99b89533d4cdf7682ea4054ad0ee36c351d05df1/src/libstd/rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  21: std::panicking::try
             at src/libstd/panicking.rs:270
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: std::rt::lang_start
             at /rustc/99b89533d4cdf7682ea4054ad0ee36c351d05df1/src/libstd/rt.rs:67
  25: neovide::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by Kethku** [comment]
I need to do a sweep over the whole code base and add useful error messages across the board for any expects or unwraps.

Thanks for the hint about the vulkan sdk. This will be very useful for install instructions.

**Comment by Kethku** [comment]
Gave better instructions in the readme.
