### ISSUE TITLE
crashing when vimrc is bad

### ISSUE THREAD

**Issue by prabirshrestha** [Kethku/neovide#32]
<details>
<summary>log</summary>

```
UI thread spawned
Ignored style attribute: "standout"
thread 'main' panicked at 'Resize failed: GenericError("Wait timeout (nvim_ui_try_resize)")', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:464
  10: std::panicking::continue_panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:139
  13: core::result::unwrap_failed
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\result.rs:1165
  14: core::result::Result<(), neovim_lib::neovim::CallError>::expect<(),neovim_lib::neovim::CallError>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\result.rs:960
  15: neovide::window::handle_new_grid_size
             at .\src\window.rs:21
  16: neovide::window::ui_loop::{{closure}}
             at .\src\window.rs:78
  17: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop.rs:211
  18: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\liballoc\boxed.rs:949
  19: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop\runner.rs:403
  20: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\panic.rs:317
  21: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\panicking.rs:287
  22: panic_unwind::__rust_maybe_catch_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
  23: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\panicking.rs:265
  24: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\panic.rs:396
  25: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop\runner.rs:401
  26: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop\runner.rs:324
  27: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop\runner.rs:72
  28: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop.rs:108
  29: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop.rs:753
  30: DefSubclassProc
  31: DefSubclassProc
  32: CallWindowProcW
  33: CallWindowProcW
  34: glPushClientAttrib
  35: CallWindowProcW
  36: SendMessageW
  37: GetWindowTextW
  38: MapWindowPoints
  39: IsCompositionActive
  40: IsCompositionActive
  41: GetWindowTextW
  42: CallWindowProcW
  43: CallWindowProcW
  44: DefSubclassProc
  45: DefSubclassProc
  46: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop.rs:726
  47: DefSubclassProc
  48: DefSubclassProc
  49: CallWindowProcW
  50: CallWindowProcW
  51: glPushClientAttrib
  52: CallWindowProcW
  53: DispatchMessageW
  54: MBToWCSEx
  55: KiUserCallbackDispatcher
  56: NtUserPeekMessage
  57: PeekMessageW
  58: PeekMessageW
  59: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop.rs:225
  60: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\platform_impl\windows\event_loop.rs:196
  61: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha6\src\event_loop.rs:148
  62: neovide::window::ui_loop
             at .\src\window.rs:62
  63: neovide::main
             at .\src\main.rs:91
  64: std::rt::lang_start::{{closure}}<()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
  65: std::rt::lang_start_internal::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:48
  66: std::panicking::try::do_call<closure-0,i32>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:287
  67: panic_unwind::__rust_maybe_catch_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
  68: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:265
  69: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panic.rs:396
  70: std::rt::lang_start_internal
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:47
  71: std::rt::lang_start<()>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
  72: main
  73: invoke_main
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  74: __scrt_common_main_seh
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  75: BaseThreadInitThunk
  76: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\neovide.exe` (exit code: 101)
```

</details>

**Comment by prabirshrestha** [comment]
Never mind seems like I had a `set completeslash=slash` in my vimrc which neovim doesn't recognize.

This is what nvim.exe terminal shows when loading, but neovide seems to crash.

![image](https://user-images.githubusercontent.com/287744/71784930-39dfba80-2fae-11ea-89ca-820c9eb4676a.png)

Might be have a better fallback story in case vimrc is bad?

**Comment by Kethku** [comment]
For sure. Definitely going to tackle this before an initial release

**Comment by prabirshrestha** [comment]
Also another I noticed is that sometimes the `nvim.exe` keeps running even though `neovide.exe` has crashed. Not a big issue now since it is pretty easy to enable the trace by using `SET RUST_BACKTRACE=1`.

**Comment by Kethku** [comment]
That's very strange. What platform?

**Comment by Kethku** [comment]
Investigated. This is a problem because the window state freezes while waiting for a return from the ui_try_resize call. I think I will need to switch to an async nvim api to solve this properly.

**Comment by Kethku** [comment]
Fixed.
