### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by GopherJ** [Kethku/neovide#332]
➜  neovide git:(master) neovide
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/cheng/.cargo/git/checkouts/skribo-3c422fce25a33836/6a8d5b7/src/collection.rs:130:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by GopherJ** [comment]
Hi, I would like to try but had this issue.

I installed through `cargo install --git https://github.com/Kethku/neovide`

**Comment by keithsim-msft** [comment]
what is guifont set to in your vim config?

**Comment by Kethku** [comment]
What guifont do you have set in your vim config?

**Comment by GopherJ** [comment]
@Kethku Hi it's here https://github.com/GopherJ/cfg/blob/225b0b40c68b9de33e23eaee527debe7e3cf4680/coc/.vimrc#L7

**Comment by Kethku** [comment]
can you give some details about your os? Does the released version have the same issue? Can you try setting RUST_BACKTRACE environment variable like the message suggests?

**Comment by GopherJ** [comment]
@Kethku HI, I use linux mint cinamon 19.3

**Comment by GopherJ** [comment]
```
➜  sbl_dispatcher git:(master) RUST_BACKTRACE=1 neovide | c
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/cheng/.cargo/git/checkouts/skribo-3c422fce25a33836/6a8d5b7/src/collection.rs:130:32
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1117
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1508
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:62
  14: <usize as core::slice::SliceIndex<[T]>>::index
             at /home/cheng/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:3116
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /home/cheng/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:2959
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /home/cheng/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:1973
  17: <skribo::collection::Itemizer as core::iter::traits::iterator::Iterator>::next
             at /home/cheng/.cargo/git/checkouts/skribo-3c422fce25a33836/6a8d5b7/src/collection.rs:130
  18: neovide::renderer::caching_shaper::CachingShaper::font_base_dimensions
             at src/renderer/caching_shaper.rs:285
  19: neovide::renderer::Renderer::new
             at src/renderer/mod.rs:36
  20: neovide::window::WindowWrapper::new
             at src/window.rs:115
  21: neovide::window::ui_loop
             at src/window.rs:414
  22: neovide::main
             at src/main.rs:58
  23: std::rt::lang_start::{{closure}}
             at /home/cheng/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  24: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by sangwonl** [comment]
same issue here.

os: WSL2 ubuntu 18.04

```
 RUST_BACKTRACE=1 cargo run --release
    Finished release [optimized + debuginfo] target(s) in 0.19s
     Running `target/release/neovide`
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/gonghee/.cargo/git/checkouts/skribo-3c422fce25a33836/6a8d5b7/src/collection.rs:130:32
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218


  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:73
  14: <usize as core::slice::SliceIndex<[T]>>::index
             at /home/gonghee/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:2872
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /home/gonghee/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:2732
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /home/gonghee/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:1942
  17: <skribo::collection::Itemizer as core::iter::traits::iterator::Iterator>::next
             at /home/gonghee/.cargo/git/checkouts/skribo-3c422fce25a33836/6a8d5b7/src/collection.rs:130
  18: neovide::renderer::caching_shaper::CachingShaper::font_base_dimensions
             at src/renderer/caching_shaper.rs:285
  19: neovide::renderer::Renderer::new
             at src/renderer/mod.rs:36
  20: neovide::window::WindowWrapper::new
             at src/window.rs:115
  21: neovide::window::ui_loop
             at src/window.rs:414
  22: neovide::main
             at src/main.rs:58
  23: std::rt::lang_start::{{closure}}
             at /home/gonghee/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  24: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by VictorRogers** [comment]
I've got this same issue too with some additional information. I installed this on both my desktop (nvidia gpu) and my lenovo t460 (intel) via yay. On my desktop, neovide ran without any issues, but my laptop produced the same error as above when building the package with yay. On the laptop, I was able to pull the release version in with yay. The release version will start successfully, but all of the characters are displayed as a [] which I think relates to some kind of font issue. I do not have any gui font settings in my .vimrc, as I normally just use console vim. I also don't think I have neovim configured to read my vimrc due to neovide being the first time I've used neovim.

**Comment by Kethku** [comment]
Can you also give some details about your install? What os are you using?

**Comment by VictorRogers** [comment]
@Kethku Arch Linux on the laptop and on my Desktop. Works on desktop but not on Laptop. I'll try to dig around for some logs on the laptop here soon.
