### ISSUE TITLE
Failed to run release on macos.

### ISSUE THREAD

**Issue by Vui-Chee** [Kethku/neovide#46]
I recently followed the instructions for macOS and even downloaded the vulcan-sdk package using brew. Unfortunately, it didn't work. The error output I got is :
```
Bridge created.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
I hope this may help you debug this issue for macOS users. Thanks!

**Comment by szbergeron** [comment]
Might be helpful for tracking this down to include the output from adding RUST_BACKTRACE=1 to envvars

**Comment by Kethku** [comment]
Interesting. Can you turn on stack traces by setting the RUST_BACKTRACE environment variable?

**Comment by yoshihitoh** [comment]
The same issue happened to me.
My environment is:
- MBP 13 inch 2018
- mac OS Mojave 10.14.6

And the backtrace is:
```
Bridge created.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic
  10: winit::platform_impl::platform::app_state::AppState::wakeup
  11: __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
  12: __CFRunLoopDoObservers
  13: __CFRunLoopRun
  14: CFRunLoopRunSpecific
  15: RunCurrentEventLoopInMode
  16: ReceiveNextEventCommon
  17: _BlockUntilNextEventMatchingListInModeWithFilter
  18: _DPSNextEvent
  19: -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
  20: -[NSApplication _doModalLoop:peek:]
  21: __35-[NSApplication runModalForWindow:]_block_invoke_2
  22: __35-[NSApplication runModalForWindow:]_block_invoke
  23: _NSTryRunModal
  24: -[NSApplication runModalForWindow:]
  25: __19-[NSAlert runModal]_block_invoke_2
  26: __19-[NSAlert runModal]_block_invoke
  27: _NSTryRunModal
  28: -[NSAlert runModal]
  29: neovide::error_handling::show_error
  30: neovide::renderer::caching_shaper::CachingShaper::get_font_pair
  31: neovide::renderer::caching_shaper::CachingShaper::font_base_dimensions
  32: neovide::renderer::Renderer::draw
  33: skulpin::renderer::renderer::Renderer::draw
  34: neovide::window::ui_loop::{{closure}}
  35: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
  36: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
  37: winit::platform_impl::platform::app_state::AppState::cleared
  38: __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
  39: __CFRunLoopDoObservers
  40: __CFRunLoopRun
  41: CFRunLoopRunSpecific
  42: RunCurrentEventLoopInMode
  43: ReceiveNextEventCommon
  44: _BlockUntilNextEventMatchingListInModeWithFilter
  45: _DPSNextEvent
  46: -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
  47: -[NSApplication run]
  48: winit::platform_impl::platform::event_loop::EventLoop<T>::run
  49: winit::event_loop::EventLoop<T>::run
  50: neovide::window::ui_loop
  51: std::rt::lang_start::{{closure}}
  52: std::panicking::try::do_call
  53: __rust_maybe_catch_panic
  54: std::rt::lang_start_internal
  55: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

explanation on error_handling::show_error is:
```
"Could not load . This font was either the font configured in init scripts via guifont, or the default font is not available on your machine. Defaults are defined here: https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs"
```

https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs#L19
`DEFAULT_FONT` is set to `Menlo`, and CachingShaper has the same font_name after initialization. But during handling `RedrawRequested` event, font_name is changed to an empty string `""`.

**Comment by Vui-Chee** [comment]
Here's my stack trace. I am running on a MBP 13 inch 2018 on macOS Catalina.
```
Bridge created.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: std::panicking::try::do_call
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
   9: core::panicking::panic
             at src/libcore/panicking.rs:70
  10: core::option::Option<T>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/macros.rs:41
  11: winit::platform_impl::platform::app_state::AppState::wakeup
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/macos/app_state.rs:214
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: neovide::error_handling::show_error
             at src/error_handling.rs:7
  31: <core::option::Option<T> as neovide::error_handling::OptionPanicExplanation<T>>::unwrap_or_explained_panic
             at src/error_handling.rs:36
  32: neovide::renderer::caching_shaper::CachingShaper::get_font_pair
             at src/renderer/caching_shaper.rs:92
  33: neovide::renderer::caching_shaper::CachingShaper::font_base_dimensions
             at src/renderer/caching_shaper.rs:174
  34: neovide::renderer::Renderer::set_font
             at src/renderer/mod.rs:40
  35: neovide::renderer::Renderer::draw
             at src/renderer/mod.rs:115
  36: neovide::window::ui_loop::{{closure}}::{{closure}}
             at src/window.rs:170
  37: skulpin::renderer::renderer::Renderer::do_draw
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/skulpin-0.5.1/src/renderer/renderer.rs:407
  38: skulpin::renderer::renderer::Renderer::draw
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/skulpin-0.5.1/src/renderer/renderer.rs:296
  39: neovide::window::ui_loop::{{closure}}
             at src/window.rs:169
  40: <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:949
  41: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/macos/app_state.rs:63
  42: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/macos/app_state.rs:162
  43: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/macos/app_state.rs:275
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: <unknown>
  48: <unknown>
  49: <unknown>
  50: <unknown>
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <() as objc::message::MessageArguments>::invoke
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  55: objc::message::platform::send_unverified
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  56: objc::message::send_message
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  57: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at ./<::objc::macros::msg_send macros>:15
  58: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/macos/event_loop.rs:89
  59: winit::event_loop::EventLoop<T>::run
             at /Users/pseudofirsthand/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/event_loop.rs:148
  60: neovide::window::ui_loop
             at src/window.rs:72
  61: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  62: std::panicking::try::do_call
  63: panic_unwind::dwarf::eh::read_encoded_pointer
  64: std::panicking::update_count_then_panic
  65: neovide::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Kethku** [comment]
Ok. I rewrote the font loading. Could you try again? I think it may be fixed.

**Comment by Vui-Chee** [comment]
Yup that works! Thanks!

**Comment by yoshihitoh** [comment]
Works well on my env too, Thank you for your great work!!
