### ISSUE TITLE
Last commit crash on linux

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#487]
Neovide just crash, this is the `BACK_TRACE`.
```
❯ RUST_BACKTRACE=1 neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/window/window_wrapper/renderer.rs:48:80
stack backtrace:
   0: rust_begin_unwind
             at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/panicking.rs:483:5
   1: core::panicking::panic_fmt
             at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/panicking.rs:85:14
   2: core::panicking::panic
             at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/option.rs:386:21
   4: neovide::window::window_wrapper::renderer::SkiaRenderer::new
             at /home/equinox/Programming/neovide/src/window/window_wrapper/renderer.rs:48:30
   5: neovide::window::window_wrapper::start_loop
             at /home/equinox/Programming/neovide/src/window/window_wrapper/mod.rs:432:25
   6: neovide::window::create_window
             at /home/equinox/Programming/neovide/src/window/mod.rs:106:5
   7: neovide::main
             at /home/equinox/Programming/neovide/src/main.rs:179:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

``` 
For reference, that concern this commit: e730a548e4bd83267ca18a6630dc8735ddaf0fb9

```
❯ RUST_BACKTRACE=full neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/window/window_wrapper/renderer.rs:48:80
stack backtrace:
   0:     0x5594a83b9770 - std::backtrace_rs::backtrace::libunwind::trace::h622bab51c72c4e69
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x5594a83b9770 - std::backtrace_rs::backtrace::trace_unsynchronized::h7e820b882ebd41ee
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5594a83b9770 - std::sys_common::backtrace::_print_fmt::h64d46258114db92f
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5594a83b9770 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h47111d0c1b5f0da5
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5594a820422c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/fmt/mod.rs:1076:17
   5:     0x5594a83b8fe1 - std::io::Write::write_fmt::h4604516fed3e5731
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/io/mod.rs:1516:15
   6:     0x5594a83b867e - std::sys_common::backtrace::_print::h785e7a78d5ef272c
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5594a83b867e - std::sys_common::backtrace::print::h108047ac5c4555d5
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5594a83b867e - std::panicking::default_hook::{{closure}}::h1d0c271f0d087ebf
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/panicking.rs:208:50
   9:     0x5594a83b867e - std::panicking::default_hook::h692753e26f11b7b7
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/panicking.rs:227:9
  10:     0x5594a83b867e - std::panicking::rust_panic_with_hook::h74ddc20305301cd9
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/panicking.rs:577:17
  11:     0x5594a83d4cf8 - std::panicking::begin_panic_handler::{{closure}}::h1a9ca6427ceee1d0
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/panicking.rs:484:9
  12:     0x5594a83d4cc4 - std::sys_common::backtrace::__rust_end_short_backtrace::h97e27b7ab754adde
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5594a83d4c7d - rust_begin_unwind
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/panicking.rs:483:5
  14:     0x5594a82019d0 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/panicking.rs:85:14
  15:     0x5594a82017ec - core::panicking::panic::h5d1c61fed2502a5f
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/panicking.rs:50:5
  16:     0x5594a81b7f3a - core::option::Option<T>::unwrap::h3df27631a6add37b
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/option.rs:386:21
  17:     0x5594a81b7f3a - neovide::window::window_wrapper::renderer::SkiaRenderer::new::hd48f9c6c47f53e29
                               at /home/equinox/Programming/neovide/src/window/window_wrapper/renderer.rs:48:30
  18:     0x5594a81b7f3a - neovide::window::window_wrapper::start_loop::hc90bf4d79ce2d295
                               at /home/equinox/Programming/neovide/src/window/window_wrapper/mod.rs:432:25
  19:     0x5594a8173ddd - neovide::window::create_window::hab8cd6afb2e98e63
                               at /home/equinox/Programming/neovide/src/window/mod.rs:106:5
  20:     0x5594a8173ddd - neovide::main::h38e9224deee3da0c
                               at /home/equinox/Programming/neovide/src/main.rs:179:5
  21:     0x5594a8161203 - core::ops::function::FnOnce::call_once::hb69c8642535ea1c9
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/core/src/ops/function.rs:227:5
  22:     0x5594a8161203 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb08ce98c17515ad5
                               at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/sys_common/backtrace.rs:125:18
  23:     0x5594a81715b5 - main
  24:     0x7f8468c51b25 - __libc_start_main
  25:     0x5594a812dcfe - _start
  26:                0x0 - <unknown>
```

**Comment by j4qfrost** [comment]
Looks like rendering switched to GL, on that commit. Do you have that dependency installed? Offending line: https://github.com/Kethku/neovide/blob/e730a548e4bd83267ca18a6630dc8735ddaf0fb9/src/window/window_wrapper/renderer.rs#L48

**Comment by kiuKisas** [comment]
Hum, probably, not sure about which dependency I need tho ?

**Comment by j4qfrost** [comment]
Did you run this? https://github.com/Kethku/neovide#debianubuntu

**Comment by Kethku** [comment]
We just swapped to opengl, so that might not be up to date.

**Comment by Kethku** [comment]
@kiuKisas what os are you running on?

**Comment by Kethku** [comment]
As a note, it requires opengl version 3.3. A thing to test would be if you can run the glutin test examples from https://github.com/rust-windowing/glutin

**Comment by Kethku** [comment]
I just pushed a change which adds a slightly different method for building the graphics backend and adds some debug expect calls. Could you try that?

**Comment by aravind2612krishna** [comment]
I trued compiling now, I still get the below error :
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, Window(OsError { line: 430, file: "/home/aravind/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/window.rs", error: XError(XError { description: "BadWindow (invalid Window parameter)", error_code: 3, request_code: 131, minor_code: 46 }) })])', src/window/window_wrapper/mod.rs:428:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/caca2121ffe4cb47d8ea2d9469c493995f57e0b5/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/caca2121ffe4cb47d8ea2d9469c493995f57e0b5/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/caca2121ffe4cb47d8ea2d9469c493995f57e0b5/library/core/src/option.rs:1300:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/caca2121ffe4cb47d8ea2d9469c493995f57e0b5/library/core/src/result.rs:1037:23
   4: neovide::window::window_wrapper::start_loop
             at ./src/window/window_wrapper/mod.rs:419:28
   5: neovide::window::create_window
             at ./src/window/mod.rs:106:5
   6: neovide::main
             at ./src/main.rs:179:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/caca2121ffe4cb47d8ea2d9469c493995f57e0b5/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Kethku** [comment]
I'm trying to build some linux (including CentOS) installs, but its taking more time and effort to get linux destros to play nice with my nvidia GPU. If anybody has the ability to dig in on this I would really love the help. I think OpenGL is the way forward because there are some linux configs that will never play nice with vulkan, but getting past the current issues would be good.

In the meantime I will create an issue representing the nebulous new gpu problems and can continue discussion there.

**Comment by Kethku** [comment]
I'm going to close this in favor of https://github.com/Kethku/neovide/issues/491
