### ISSUE TITLE
Thread 'main' panicked

### ISSUE THREAD

**Issue by en1tan** [Kethku/neovide#575]
OS: `5.11.14-arch1-1`
Gfx Card: `AMD REDWOOD (DRM 2.50.0 / 5.11.14-arch1-1, LLVM 11.1.0)`
neovide: installed `neovide-git` from aur

```thread 'main' panicked at 'Failed to create renderer: VkError(ERROR_INITIALIZATION_FAILED)', src/window/sdl2/mod.rs:458:14 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by Kethku** [comment]
This is a vulkan driver issue. What happens if you try from the opengl branch?

**Comment by en1tan** [comment]
still same issue

**Comment by Kethku** [comment]
I've encountered this before. Can you try attaching a debugger? Weirdly on some linux machines I've found that to fix the segmentation fault. No idea why or even how there is a segmentation fault here at all given rusts guard rails

**Comment by en1tan** [comment]
Can you show me the steps to do this? no idea

**Comment by ouuan** [comment]
I've encountered the same issue. The commit is 7b2418b and here's the gdb output:

```
Thread 1 "neovide" received signal SIGSEGV, Segmentation fault.
0x00005555563f36c3 in GrGLExtensions::init(GrGLStandard, GrGLFunction<unsigned char const* (unsigned int)>, GrGLFunction<unsigned char const* (unsigned int, unsigned int)>, GrGLFunction<void (unsigned int, int*)>, GrGLFunction<char const* (void*, int)>, void*) ()
(gdb) bt
#0  0x00005555563f36c3 in GrGLExtensions::init(GrGLStandard, GrGLFunction<unsigned char const* (unsigned int)>, GrGLFunction<unsigned char const* (unsigned int, unsigned int)>, GrGLFunction<void (unsigned int, int*)>, GrGLFunction<char const* (void*, int)>, void*) ()
#1  0x0000555556602801 in GrGLMakeAssembledGLInterface(void*, void (*(*)(void*, char const*))()) ()
#2  0x0000555556592070 in GrGLMakeAssembledInterface(void*, void (*(*)(void*, char const*))()) ()
#3  0x000055555646fa45 in C_GrGLInterface_MakeAssembledInterface ()
#4  0x000055555585c6b8 in skia_safe::prelude::RCHandle<skia_bindings::bindings::GrGLInterface>::new_load_with<closure-1> (loadfn=...)
    at /home/ouuan/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-safe-0.38.3/src/gpu/gl/interface.rs:24
#5  0x0000555555798bb4 in neovide::window::window_wrapper::renderer::SkiaRenderer::new (windowed_context=0x7fffffffbf90)
    at /home/ouuan/GitHub/neovide/src/window/window_wrapper/renderer.rs:53
#6  0x00005555557f59ae in neovide::window::window_wrapper::start_loop (window_command_receiver=..., ui_command_sender=..., running=Arc(strong=3, weak=0) = {...}, 
    logical_size=..., renderer=...) at /home/ouuan/GitHub/neovide/src/window/window_wrapper/mod.rs:435
#7  0x000055555583b27d in neovide::window::create_window (batched_draw_command_receiver=..., window_command_receiver=..., ui_command_sender=..., 
    running=Arc(strong=3, weak=0) = {...}) at /home/ouuan/GitHub/neovide/src/window/mod.rs:106
#8  0x000055555577ccf2 in neovide::main () at /home/ouuan/GitHub/neovide/src/main.rs:179
```

**Comment by ouuan** [comment]
I succeeded to start neovide after switching from nvidia to nouveau.

**Comment by en1tan** [comment]
oh, I don't use an nvidia card

**Comment by Kethku** [comment]
These have been fixed in main.
