### ISSUE TITLE
Fails to run neovide after following the steps of installation linux mint 19.1

### ISSUE THREAD

**Issue by revoltez** [Kethku/neovide#579]
i have followed the steps provided in this repository and it throws the following error whenever i run ./home/user/neovide/target/release/neovide :

```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_EXTENSION_NOT_PRESENT)))', src/window/sdl2/mod.rs:458:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by Kethku** [comment]
This is a vulkan error. Can you try the opengl branch?

**Comment by qazip** [comment]
```
❯ neovide                 
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_EXTENSION_NOT_PRESENT)))', src/window/sdl2/mod.rs:456:14
stack backtrace:
   0:     0x55a1185cf840 - <unknown>
   1:     0x55a1184f516c - <unknown>
   2:     0x55a1185cf0b1 - <unknown>
   3:     0x55a1185cea15 - <unknown>
   4:     0x55a1185ce0fa - <unknown>
   5:     0x55a1185ed5f8 - <unknown>
   6:     0x55a1185ed56c - <unknown>
   7:     0x55a1185ed51d - <unknown>
   8:     0x55a1184f34c0 - <unknown>
   9:     0x55a1184f9702 - <unknown>
  10:     0x55a1184c8e44 - <unknown>
  11:     0x55a1184b2c54 - <unknown>
  12:     0x55a118449213 - <unknown>
  13:     0x55a1184af345 - <unknown>
  14:     0x7f92620b9b25 - __libc_start_main
  15:     0x55a11841077e - <unknown>
  16:                0x0 - <unknown>
```

**Comment by qazip** [comment]
I installed the opengl branch, following the steps in the README and I am having exactly the same problem as before:
```

❯ neovide          
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_EXTENSION_NOT_PRESENT)))', src/window/sdl2/mod.rs:456:14
stack backtrace:
   0:     0x561a70a1c840 - <unknown>
   1:     0x561a7094216c - <unknown>
   2:     0x561a70a1c0b1 - <unknown>
   3:     0x561a70a1ba15 - <unknown>
   4:     0x561a70a1b0fa - <unknown>
   5:     0x561a70a3a5f8 - <unknown>
   6:     0x561a70a3a56c - <unknown>
   7:     0x561a70a3a51d - <unknown>
   8:     0x561a709404c0 - <unknown>
   9:     0x561a70946702 - <unknown>
  10:     0x561a70915e44 - <unknown>
  11:     0x561a708ffc54 - <unknown>
  12:     0x561a70896213 - <unknown>
  13:     0x561a708fc345 - <unknown>
  14:     0x7f770157fb25 - __libc_start_main
  15:     0x561a7085d77e - <unknown>
  16:                0x0 - <unknown>
```

I am using arch and installed by following https://github.com/Kethku/neovide#with-non-default-branch..

**Comment by qazip** [comment]
It seems like the 4th line in https://github.com/Kethku/neovide#with-non-default-branch doesn't actually change the PKGBUILD file. I changed it myself and re-installed. I have a new error now:
```

❯ neovide          
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/fonts/caching_shaper.rs:59:14
stack backtrace:
   0:     0x555dadc83150 - <unknown>
   1:     0x555dadaef1dc - <unknown>
   2:     0x555dadc829c1 - <unknown>
   3:     0x555dadc82325 - <unknown>
   4:     0x555dadc81a0a - <unknown>
   5:     0x555dadca0eee - <unknown>
   6:     0x555dadca0e8c - <unknown>
   7:     0x555dadca0e3d - <unknown>
   8:     0x555dadaec990 - <unknown>
   9:     0x555dadaec7ac - <unknown>
  10:     0x555dada1ea36 - <unknown>
  11:     0x555dada1e79a - <unknown>
  12:     0x555dada5be49 - <unknown>
  13:     0x555dada53aa3 - <unknown>
  14:     0x555dada59025 - <unknown>
  15:     0x7efd16f28b25 - __libc_start_main
  16:     0x555dada1cd5e - <unknown>
  17:                0x0 - <unknown>
```

**Comment by qazip** [comment]
After installing the ubuntu-font-family (pacman -Sy ttf-ubuntu-font-family), I am now only having:

```
❯ neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
[1]    362895 segmentation fault (core dumped)  neovide
```

Any suggestions?

**Comment by Kethku** [comment]
These have been fixed in main
