### ISSUE TITLE
Cannot compile on FreeBSD 13.0-RELEASE

### ISSUE THREAD

**Issue by atisharma** [Kethku/neovide#628]
As per title.

```
$ RUST_BACKTRACE=1 cargo build --release
   Compiling sdl2-sys v0.34.4
   Compiling skia-bindings v0.32.1
   Compiling futures-executor v0.3.12
   Compiling smithay-client-toolkit v0.6.6
error: failed to run custom build command for `skia-bindings v0.32.1`

Caused by:
  process didn't exit successfully: `/darkstar/sync/projects/neovide/target/release/build/skia-bindings-4775d0867e4a49d9/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: x86_64-unknown-freebsd

  --- stderr
  thread 'main' panicked at 'unsupported target: Target { architecture: "x86_64", vendor: "unknown", system: "freebsd", abi: None }', /home/asharma/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.32.1/build_support/skia.rs:403:18
  stack backtrace:
     0: rust_begin_unwind
     1: std::panicking::begin_panic_fmt
     2: build_script_build::build_support::skia::BinariesConfiguration::from_cargo_env
               at /home/asharma/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.32.1/build_support/skia.rs:403:18
     3: build_script_build::main
               at /home/asharma/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.32.1/build.rs:53:27
     4: core::ops::function::FnOnce::call_once
               at /wrkdirs/usr/ports/lang/rust/work/rustc-1.51.0-src/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Kethku** [comment]
This is an upstream issue. I'm not sure FreeBSD is supported in upstream skia-safe

**Comment by j4qfrost** [comment]
A quick hack might be to trick the compiler into building skia as inux. It looks like the code for linux should be compatible with BSD, but I would have to do a lot of investigation, which I don't want to try atm. Good luck.

**Comment by Kethku** [comment]
I looked online and there appears to be a bunch of issues with building skia natively for free bsd. So I'm going to close this as not supported. If somebody wants to take this on as a project though I'd be happy to merge some PRs.
