### ISSUE TITLE
Index out of bound error during font loading

### ISSUE THREAD

**Issue by kiritsuku** [Kethku/neovide#670]
I built&ran neovide (on ubuntu 20.04) but it immediately crashed. Some problem with font rendering/caching:

```
% ./neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/liaraschafer/.cargo/git/checkouts/skribo-3c422fce25a33836/a35c876/src/collection.rs:130:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/slice/index.rs:182:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/vec/mod.rs:2381:9
   6: <skribo::collection::Itemizer as core::iter::traits::iterator::Iterator>::next
             at /home/liaraschafer/.cargo/git/checkouts/skribo-3c422fce25a33836/a35c876/src/collection.rs:130:32
   7: skribo::session::LayoutSession<S>::create
             at /home/liaraschafer/.cargo/git/checkouts/skribo-3c422fce25a33836/a35c876/src/session.rs:77:34
   8: neovide::renderer::fonts::caching_shaper::CachingShaper::shape
             at /home/liaraschafer/dev/neovide/src/renderer/fonts/caching_shaper.rs:105:23
   9: neovide::renderer::fonts::caching_shaper::CachingShaper::shape_cached
             at /home/liaraschafer/dev/neovide/src/renderer/fonts/caching_shaper.rs:137:25
  10: neovide::renderer::Renderer::draw_foreground
             at /home/liaraschafer/dev/neovide/src/renderer/mod.rs:185:25
  11: neovide::renderer::rendered_window::RenderedWindow::handle_window_draw_command
             at /home/liaraschafer/dev/neovide/src/renderer/rendered_window.rs:466:21
  12: neovide::renderer::Renderer::handle_draw_command
             at /home/liaraschafer/dev/neovide/src/renderer/mod.rs:221:25
  13: neovide::renderer::Renderer::draw_frame
             at /home/liaraschafer/dev/neovide/src/renderer/mod.rs:282:13
  14: neovide::window::window_wrapper::Sdl2WindowWrapper::draw_frame::{{closure}}
             at /home/liaraschafer/dev/neovide/src/window/sdl2/mod.rs:369:24
  15: skulpin_renderer::renderer::Renderer::do_draw
             at /home/liaraschafer/.cargo/registry/src/github.com-1ecc6299db9ec823/skulpin-renderer-0.5.2/src/renderer.rs:498:13
  16: skulpin_renderer::renderer::Renderer::draw
             at /home/liaraschafer/.cargo/registry/src/github.com-1ecc6299db9ec823/skulpin-renderer-0.5.2/src/renderer.rs:379:22
  17: neovide::window::window_wrapper::Sdl2WindowWrapper::draw_frame
             at /home/liaraschafer/dev/neovide/src/window/sdl2/mod.rs:366:13
  18: neovide::window::window_wrapper::start_loop
             at /home/liaraschafer/dev/neovide/src/window/sdl2/mod.rs:504:15
  19: neovide::window::create_window
             at /home/liaraschafer/dev/neovide/src/window/mod.rs:112:5
  20: neovide::main
             at /home/liaraschafer/dev/neovide/src/main.rs:182:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by j4qfrost** [comment]
If you install noto-fonts, it should work. There is a snap for neovide that
works out of the box in the beta channel, which will be pushed into stable
when opengl gets merged to main.

**Comment by kiritsuku** [comment]
Yes, installing `noto-fonts` solved the issue. Thanks.

**Comment by Kethku** [comment]
In that case, closing in favor of font fallback issue (and the interim fix in opengl branch)
