### ISSUE TITLE
Neovide fails to run on KDE and xmonad after installing from AUR

### ISSUE THREAD

**Issue by AayanTDE** [Kethku/neovide#707]
```
aayan@arch ~> neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_EXTENSION_NOT_PRESENT)))', src/window/sdl2/mod.rs:456:14
stack backtrace:
   0:     0x556c596b09c0 - <unknown>
   1:     0x556c5954600c - <unknown>
   2:     0x556c596b0221 - <unknown>
   3:     0x556c596afb85 - <unknown>
   4:     0x556c596aef9c - <unknown>
   5:     0x556c596ce2d8 - <unknown>
   6:     0x556c596ce24c - <unknown>
   7:     0x556c596ce1fd - <unknown>
   8:     0x556c59544360 - <unknown>
   9:     0x556c5954a722 - <unknown>
  10:     0x556c595a219b - <unknown>
  11:     0x556c59521291 - <unknown>
  12:     0x556c595943d3 - <unknown>
  13:     0x556c59521e16 - <unknown>
  14:     0x7fcdbb219b25 - __libc_start_main
  15:     0x556c594f5dce - <unknown>
  16:                0x0 - <unknown>
```

**Comment by PyGamer0** [comment]
Try the opengl branch

**Comment by AayanTDE** [comment]
> Try the opengl branch

Now there's another bug
```
aayan@arch ~> neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/fonts/font_loader.rs:55:14
stack backtrace:
   0:     0x55dea88ee830 - <unknown>
   1:     0x55dea8661cfc - <unknown>
   2:     0x55dea88ee091 - <unknown>
   3:     0x55dea88ed9f5 - <unknown>
   4:     0x55dea88ece0c - <unknown>
   5:     0x55dea890c12e - <unknown>
   6:     0x55dea890c0cc - <unknown>
   7:     0x55dea890c07d - <unknown>
   8:     0x55dea865f550 - <unknown>
   9:     0x55dea865f36c - <unknown>
  10:     0x55dea8827d38 - <unknown>
  11:     0x55dea87f63c5 - <unknown>
  12:     0x55dea87f627f - <unknown>
  13:     0x55dea87babf3 - <unknown>
  14:     0x55dea875bb1e - <unknown>
  15:     0x55dea87e52a4 - <unknown>
  16:     0x55dea881c3c9 - <unknown>
  17:     0x55dea87e5002 - <unknown>
  18:     0x55dea875fe4a - <unknown>
  19:     0x55dea875e94e - <unknown>
  20:     0x55dea88045dc - <unknown>
  21:     0x55dea87e08d3 - <unknown>
  22:     0x55dea8800bb6 - <unknown>
  23:     0x7f3e85086b25 - __libc_start_main
  24:     0x55dea85e4d5e - <unknown>
  25:                0x0 - <unknown>
```

**Comment by PyGamer0** [comment]
try installing noto font?

**Comment by AayanTDE** [comment]
> try installing noto font?

Turns out I had a bad line in my .vimrc, which I removed and neovide launches. An unrelated issue though, I am unable to type "!" in the colon prompt. (eg I can't type :q! only :q)

**Comment by Kethku** [comment]
Thats a known issue tracked elsewhere. As soon as opengl merges, going up the list of priorities.

**Comment by Kethku** [comment]
Closing this as repeat of other known issues, but feel free to respond here if you have more questions.
