### ISSUE TITLE
[Linux] Debug build results in OOB array access

### ISSUE THREAD

**Issue by osa1** [Kethku/neovide#72]
```
$ RUST_BACKTRACE=1 ./target/debug/neovide
thread 'main' panicked at 'index out of bounds: the len is 28 but the index is 30', /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libcore/slice/mod.rs:2791:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:463
  11: rust_begin_unwind
             at src/libstd/panicking.rs:371
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  14: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libcore/slice/mod.rs:2791
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libcore/slice/mod.rs:2656
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/liballoc/vec.rs:1882
  17: neovide::renderer::cursor_renderer::CursorRenderer::draw
             at src/renderer/cursor_renderer.rs:204
  18: neovide::renderer::Renderer::draw
             at src/renderer/mod.rs:150
  19: neovide::window::ui_loop::{{closure}}::{{closure}}
             at src/window.rs:175
  20: skulpin::renderer::renderer::Renderer::do_draw
             at /home/omer/.cargo/git/checkouts/skulpin-fd2a67126990d740/c0b1948/src/renderer/renderer.rs:408
  21: skulpin::renderer::renderer::Renderer::draw
             at /home/omer/.cargo/git/checkouts/skulpin-fd2a67126990d740/c0b1948/src/renderer/renderer.rs:297
  22: neovide::window::ui_loop::{{closure}}
             at src/window.rs:174
  23: winit::platform_impl::platform::sticky_exit_callback
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/linux/mod.rs:701
  24: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/linux/x11/mod.rs:315
  25: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/linux/x11/mod.rs:398
  26: winit::platform_impl::platform::EventLoop<T>::run
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/linux/mod.rs:648
  27: winit::event_loop::EventLoop<T>::run
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/event_loop.rs:148
  28: neovide::window::ui_loop
             at src/window.rs:71
  29: neovide::main
             at src/main.rs:23
  30: std::rt::lang_start::{{closure}}
  31: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  32: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  34: std::panicking::try
             at src/libstd/panicking.rs:272
  35: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  36: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  37: std::rt::lang_start
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libstd/rt.rs:67
  38: main
  39: __libc_start_main
  40: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Kethku** [comment]
Do you have any details about when this happened?

**Comment by osa1** [comment]
This happens right away when I run a debug build. So `./target/debug/neovide` crashes with this immediately.

**Comment by Kethku** [comment]
Should be fixed now.

**Comment by Kethku** [comment]
Closing this as I believe it is fixed. Please reopen if you are still running into it.
