### ISSUE TITLE
[Linux] Provide --help flag option

### ISSUE THREAD

**Issue by hissssst** [Kethku/neovide#83]
```
$ neovide --help                                                                                                                                                                                                 
Error: 'Error reading message'
thread 'tokio-runtime-worker' panicked at 'Could not communicate.: Could not communicate with neovim process: Error decoding response to request 'nvim_set_var'', src/error_handling.rs:5:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
$ neovide -h                                                                                                                                                                                                    
Error: 'Error reading message'
thread 'tokio-runtime-worker' panicked at 'Could not communicate.: Could not communicate with neovim process: Error decoding response to request 'nvim_set_var'', src/error_handling.rs:5:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by Kethku** [comment]
At the moment all arguments are passed on to the nvim process. I haven't had a command argument yet that isn't already documented in nvim

**Comment by Kethku** [comment]
Although this indicates that that isn't working..

**Comment by Kethku** [comment]
That error says you are running too old of a neovim though. I should really check that and give a better error...

**Comment by Kethku** [comment]
I added a version error message and will add more commands once neovide actually has any.
